package model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;

// This class represents a Budget entity in the database, mapped to the 'budget' table.
@Entity
public class Budget {
    
    // The 'id' field is the primary key for this entity. It will be auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The 'category' field represents the budget category (e.g., 'Groceries', 'Entertainment')
    private String category;
    
    // The 'amount' field represents the budgeted amount for the given category.
    private Double amount;
    
    // The 'month' field represents the month for which the budget is set (e.g., 1 for January, 2 for February).
    private Integer month;
    
    // The 'year' field represents the year for the budget (e.g., 2024).
    private Integer year;

    // The 'user' field is a many-to-one relationship with the User entity.
    // A budget is associated with exactly one user.
    @ManyToOne
    @JoinColumn(name = "user_id", referencedColumnName = "id", nullable = false)  // Foreign key column to link to the User entity
    @JsonBackReference  // Prevents circular reference during JSON serialization (ignores the user field in the User object when serializing Budget)
    private User user;
    
    // Getter for 'id' field
    public Long getId() {
        return id;
    }
    
    // Setter for 'id' field
    public void setId(Long id) {
        this.id = id;
    }
    
    // Getter for 'category' field
    public String getCategory() {
        return category;
    }
    
    // Setter for 'category' field
    public void setCategory(String category) {
        this.category = category;
    }
    
    // Getter for 'amount' field
    public Double getAmount() {
        return amount;
    }
    
    // Setter for 'amount' field
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    
    // Getter for 'month' field
    public Integer getMonth() {
        return month;
    }
    
    // Setter for 'month' field
    public void setMonth(Integer month) {
        this.month = month;
    }
    
    // Getter for 'year' field
    public Integer getYear() {
        return year;
    }
    
    // Setter for 'year' field
    public void setYear(Integer year) {
        this.year = year;
    }
    
    // Getter and Setter for the 'user' field (many-to-one relationship with User)
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    
    // Override the toString method to return a human-readable string representation of the Budget object
    @Override
    public String toString() {
        return "Budget [id=" + id + ", category=" + category + ", amount=" + amount + ", month=" + month + ", year=" + year + "]";
    }
}
