package model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;

// This class represents an Expense entity, which is mapped to a table in the database.
@Entity
public class Expense {
    
    // The 'id' field is the primary key for this entity and is auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The 'amount' field represents the expense amount (e.g., the cost of a purchase).
    private Double amount;

    // The 'category' field represents the category of the expense (e.g., 'Food', 'Transport').
    private String category;

    // The 'description' field provides a detailed description of the expense.
    private String description;

    // The 'month' field represents the month when the expense occurred (e.g., 1 for January, 2 for February).
    private Integer month;

    // The 'year' field represents the year when the expense occurred (e.g., 2024).
    private Integer year;

    // The 'user' field represents a many-to-one relationship with the User entity.
    // Each expense is associated with a specific user.
    @ManyToOne
    @JoinColumn(name = "user_id", referencedColumnName = "id", nullable = false)  // Foreign key column linking to the User entity
    @JsonBackReference  // Prevents circular reference when serializing to JSON (ignores 'user' when serializing 'Expense')
    private User user;

    // Getter and Setter for 'id' field (primary key)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    // Getter and Setter for 'amount' field
    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    // Getter and Setter for 'category' field
    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    // Getter and Setter for 'description' field
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // Getter and Setter for 'month' field
    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }

    // Getter and Setter for 'year' field
    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    // Getter and Setter for 'user' field (many-to-one relationship with the User entity)
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
